---
name: SysMon builds

on:
  push:
    branches:
      - master

env:
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          args: --timeout=5m
